title: joseph's blog
email: sidnancy81@gmail.com
description: >-
  블로그 설명
baseurl: ""
url: "https://joseph-jy.github.io"
twitter_username: cooljoseph
github_username: joseph-jy

repository: joseph-jy/joseph-jy.github.io

remote_theme: riggraz/no-style-please

permalink: /:title/

theme_config:
  appearance: auto
  date_format: "%Y-%m-%d"
  show_description: true
  no_b_hierarchies: false

sass:
  style: compressed

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
